parrot="Norweegian Blue"
print(parrot[0:6])
print(parrot[3:5])
print(parrot[0:9])
print(parrot[:9])
print(parrot[10:14])
print(parrot[10:])
print(parrot[:6])
print(parrot[6:])
print(parrot[:])
print(parrot[-14:-8])
print(parrot[-4:-2])
print(parrot[-4:12])